name: pipeline-env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base
  - python=3.6.9
  - illumina-interop
  - pip
  - pip:
    - matplotlib
    - seaborn
    - cython
    - numpy
    - scipy
    - nltk
    - line_profiler
    - memory_profiler
    - plotly
    - cufflinks
    - scikit-learn
    - statsmodels
    - pandas==1.1.0
    - jupyter
    - jupyterlab
    - ipywidgets
