name: pipeline-env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base==3.5.2
  - python=3.6.0
  - illumina-interop
  - pip
  - pip:
    - rpy2==2.9.5
    - matplotlib
    - seaborn
    - cython
    - numpy
    - scipy
    - nltk
    - line_profiler
    - memory_profiler
    - plotly
    - cufflinks
    - scikit-learn
    - statsmodels
    - pandas==0.23.0
    - jupyter
    - jupyterlab
    - ipywidgets
